name: Deployment

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 0
      - name: Setup Nodejs Environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install --no-audit --no-fund --no-optional
      - name: Run a multiline script
        run: |
          echo test the checkout action,
          ls -a
