name: Deployment

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: action/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Nodejs Environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install --no-audit --no-found --no-optional
      - name: Deploy init
        run: npm run deploy
